FROM python:3.12-slim

# RUN apt-get update && apt-get install -y curl git vim net-tools build-essential

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg curl -y pkg-config libhdf5-dev

RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

RUN apt-get update && apt-get install -y git vim net-tools build-essential google-cloud-cli=473.0.0-0

WORKDIR /code

RUN mkdir -p /tmp/dataset2 /tmp/tflite

ENV PYTHONPATH=/code/src